version: "3.5"

x-marketplace: &marketplace-backend
  build:
    context: .
    dockerfile: Dockerfile
  image: marketplace-backend
  restart: unless-stopped
  environment:
    POSTGRES_URL: 'postgres://marketplace:12345@marketplace-postgres:5432/marketplace_db'
    API_PORT: '5000'
    DISABLE_SECURITY: 'false'
    ESCROW_SEED: '//Alice'
    UNIQUE_WS_ENDPOINT: 'ws://localhost:9944'
    UNIQUE_NETWORK: 'private_opal'
    UNIQUE_START_FROM_BLOCK: 'current'
    CONTRACT_ETH_OWNER_SEED: 'Get by running "npm run playground deploy_contract"'
    CONTRACT_ADDRESS: 'Get by running "npm run playground deploy_contract"'
    UNIQUE_COLLECTION_IDS: '1, 2, 3'
    KUSAMA_WS_ENDPOINT: 'wss://ws-relay-opal.unique.network'
    KUSAMA_NETWORK: 'private_ksm'
    KUSAMA_START_FROM_BLOCK: 'current'
    COMMISSION_PERCENT: '10'
    AUTO_DB_MIGRATIONS: 'false'

services:
  marketplace-postgres:
    image: postgres:14.1-alpine
    container_name: marketplace-postgres
    environment:
      POSTGRES_DB: 'marketplace_db'
      POSTGRES_USER: 'marketplace'
      POSTGRES_PASSWORD: '12345'
      POSTGRES_PORT: '5432'
      POSTGRES_INITDB_ARGS: "--auth-local=trust"
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ../postgresql/marketplace:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

  marketplace-web:
    container_name: marketplace-web
    ports:
      - 5000:5000
    <<: *marketplace-backend

  marketplace-escrow-unique:
    container_name: marketplace-escrow-unique
    command: [ "npm", "run", "escrow:unique" ]
    <<: *marketplace-backend

  marketplace-escrow-kusama:
    container_name: marketplace-escrow-kusama
    command: [ "npm", "run", "escrow:kusama" ]
    <<: *marketplace-backend

  postgres-test:
    image: postgres:14.1-alpine
    container_name: test-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgresman
      POSTGRES_PASSWORD: test12345
      POSTGRES_PORT: 5432
      POSTGRES_INITDB_ARGS: "--auth-local=trust"
    ports:
      - 6432:5432
